name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client  # Specify the directory where package.json is located

      - name: Build
        run: npm run build
        working-directory: ./client  # Use the same directory for build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/build  # Adjust according to your project's build output directory within the client folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
