name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Ensure compatibility with your project

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Compiles TypeScript, SCSS to CSS, and produces a production build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build # Make sure this matches your project's build output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
